// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	vo "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/vo"
	mock "github.com/stretchr/testify/mock"
)

// MockINewsProxy is an autogenerated mock type for the INewsProxy type
type MockINewsProxy struct {
	mock.Mock
}

type MockINewsProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockINewsProxy) EXPECT() *MockINewsProxy_Expecter {
	return &MockINewsProxy_Expecter{mock: &_m.Mock}
}

// FetchNews provides a mock function with given fields: ctx, searchKeyword
func (_m *MockINewsProxy) FetchNews(ctx context.Context, searchKeyword string) ([]vo.NewsVo, error) {
	ret := _m.Called(ctx, searchKeyword)

	if len(ret) == 0 {
		panic("no return value specified for FetchNews")
	}

	var r0 []vo.NewsVo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]vo.NewsVo, error)); ok {
		return rf(ctx, searchKeyword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []vo.NewsVo); ok {
		r0 = rf(ctx, searchKeyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vo.NewsVo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, searchKeyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockINewsProxy_FetchNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchNews'
type MockINewsProxy_FetchNews_Call struct {
	*mock.Call
}

// FetchNews is a helper method to define mock.On call
//   - ctx context.Context
//   - searchKeyword string
func (_e *MockINewsProxy_Expecter) FetchNews(ctx interface{}, searchKeyword interface{}) *MockINewsProxy_FetchNews_Call {
	return &MockINewsProxy_FetchNews_Call{Call: _e.mock.On("FetchNews", ctx, searchKeyword)}
}

func (_c *MockINewsProxy_FetchNews_Call) Run(run func(ctx context.Context, searchKeyword string)) *MockINewsProxy_FetchNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockINewsProxy_FetchNews_Call) Return(_a0 []vo.NewsVo, _a1 error) *MockINewsProxy_FetchNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockINewsProxy_FetchNews_Call) RunAndReturn(run func(context.Context, string) ([]vo.NewsVo, error)) *MockINewsProxy_FetchNews_Call {
	_c.Call.Return(run)
	return _c
}

// ProviderName provides a mock function with no fields
func (_m *MockINewsProxy) ProviderName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProviderName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockINewsProxy_ProviderName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProviderName'
type MockINewsProxy_ProviderName_Call struct {
	*mock.Call
}

// ProviderName is a helper method to define mock.On call
func (_e *MockINewsProxy_Expecter) ProviderName() *MockINewsProxy_ProviderName_Call {
	return &MockINewsProxy_ProviderName_Call{Call: _e.mock.On("ProviderName")}
}

func (_c *MockINewsProxy_ProviderName_Call) Run(run func()) *MockINewsProxy_ProviderName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockINewsProxy_ProviderName_Call) Return(_a0 string) *MockINewsProxy_ProviderName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockINewsProxy_ProviderName_Call) RunAndReturn(run func() string) *MockINewsProxy_ProviderName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockINewsProxy creates a new instance of MockINewsProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockINewsProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockINewsProxy {
	mock := &MockINewsProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
