// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/entities"

	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIAnalysisEventRepository is an autogenerated mock type for the IAnalysisEventRepository type
type MockIAnalysisEventRepository struct {
	mock.Mock
}

type MockIAnalysisEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAnalysisEventRepository) EXPECT() *MockIAnalysisEventRepository_Expecter {
	return &MockIAnalysisEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, analysisEvent
func (_m *MockIAnalysisEventRepository) Create(ctx context.Context, analysisEvent *entities.AnalysisEvent) error {
	ret := _m.Called(ctx, analysisEvent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.AnalysisEvent) error); ok {
		r0 = rf(ctx, analysisEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAnalysisEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAnalysisEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - analysisEvent *entities.AnalysisEvent
func (_e *MockIAnalysisEventRepository_Expecter) Create(ctx interface{}, analysisEvent interface{}) *MockIAnalysisEventRepository_Create_Call {
	return &MockIAnalysisEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, analysisEvent)}
}

func (_c *MockIAnalysisEventRepository_Create_Call) Run(run func(ctx context.Context, analysisEvent *entities.AnalysisEvent)) *MockIAnalysisEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.AnalysisEvent))
	})
	return _c
}

func (_c *MockIAnalysisEventRepository_Create_Call) Return(_a0 error) *MockIAnalysisEventRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAnalysisEventRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.AnalysisEvent) error) *MockIAnalysisEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FailAllRunning provides a mock function with given fields: ctx, failureReason, finishedAt
func (_m *MockIAnalysisEventRepository) FailAllRunning(ctx context.Context, failureReason string, finishedAt time.Time) error {
	ret := _m.Called(ctx, failureReason, finishedAt)

	if len(ret) == 0 {
		panic("no return value specified for FailAllRunning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, failureReason, finishedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAnalysisEventRepository_FailAllRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailAllRunning'
type MockIAnalysisEventRepository_FailAllRunning_Call struct {
	*mock.Call
}

// FailAllRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - failureReason string
//   - finishedAt time.Time
func (_e *MockIAnalysisEventRepository_Expecter) FailAllRunning(ctx interface{}, failureReason interface{}, finishedAt interface{}) *MockIAnalysisEventRepository_FailAllRunning_Call {
	return &MockIAnalysisEventRepository_FailAllRunning_Call{Call: _e.mock.On("FailAllRunning", ctx, failureReason, finishedAt)}
}

func (_c *MockIAnalysisEventRepository_FailAllRunning_Call) Run(run func(ctx context.Context, failureReason string, finishedAt time.Time)) *MockIAnalysisEventRepository_FailAllRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIAnalysisEventRepository_FailAllRunning_Call) Return(_a0 error) *MockIAnalysisEventRepository_FailAllRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAnalysisEventRepository_FailAllRunning_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockIAnalysisEventRepository_FailAllRunning_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, analysisEventID
func (_m *MockIAnalysisEventRepository) FindByID(ctx context.Context, analysisEventID uint) (*entities.AnalysisEvent, error) {
	ret := _m.Called(ctx, analysisEventID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.AnalysisEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.AnalysisEvent, error)); ok {
		return rf(ctx, analysisEventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.AnalysisEvent); ok {
		r0 = rf(ctx, analysisEventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AnalysisEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, analysisEventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAnalysisEventRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAnalysisEventRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - analysisEventID uint
func (_e *MockIAnalysisEventRepository_Expecter) FindByID(ctx interface{}, analysisEventID interface{}) *MockIAnalysisEventRepository_FindByID_Call {
	return &MockIAnalysisEventRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, analysisEventID)}
}

func (_c *MockIAnalysisEventRepository_FindByID_Call) Run(run func(ctx context.Context, analysisEventID uint)) *MockIAnalysisEventRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIAnalysisEventRepository_FindByID_Call) Return(_a0 *entities.AnalysisEvent, _a1 error) *MockIAnalysisEventRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAnalysisEventRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*entities.AnalysisEvent, error)) *MockIAnalysisEventRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestReusable provides a mock function with given fields: ctx, symbol, category
func (_m *MockIAnalysisEventRepository) FindLatestReusable(ctx context.Context, symbol string, category string) (*entities.AnalysisEvent, error) {
	ret := _m.Called(ctx, symbol, category)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestReusable")
	}

	var r0 *entities.AnalysisEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.AnalysisEvent, error)); ok {
		return rf(ctx, symbol, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.AnalysisEvent); ok {
		r0 = rf(ctx, symbol, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AnalysisEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAnalysisEventRepository_FindLatestReusable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestReusable'
type MockIAnalysisEventRepository_FindLatestReusable_Call struct {
	*mock.Call
}

// FindLatestReusable is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - category string
func (_e *MockIAnalysisEventRepository_Expecter) FindLatestReusable(ctx interface{}, symbol interface{}, category interface{}) *MockIAnalysisEventRepository_FindLatestReusable_Call {
	return &MockIAnalysisEventRepository_FindLatestReusable_Call{Call: _e.mock.On("FindLatestReusable", ctx, symbol, category)}
}

func (_c *MockIAnalysisEventRepository_FindLatestReusable_Call) Run(run func(ctx context.Context, symbol string, category string)) *MockIAnalysisEventRepository_FindLatestReusable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIAnalysisEventRepository_FindLatestReusable_Call) Return(_a0 *entities.AnalysisEvent, _a1 error) *MockIAnalysisEventRepository_FindLatestReusable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAnalysisEventRepository_FindLatestReusable_Call) RunAndReturn(run func(context.Context, string, string) (*entities.AnalysisEvent, error)) *MockIAnalysisEventRepository_FindLatestReusable_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, analysisEvent
func (_m *MockIAnalysisEventRepository) Update(ctx context.Context, analysisEvent *entities.AnalysisEvent) error {
	ret := _m.Called(ctx, analysisEvent)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.AnalysisEvent) error); ok {
		r0 = rf(ctx, analysisEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAnalysisEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAnalysisEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - analysisEvent *entities.AnalysisEvent
func (_e *MockIAnalysisEventRepository_Expecter) Update(ctx interface{}, analysisEvent interface{}) *MockIAnalysisEventRepository_Update_Call {
	return &MockIAnalysisEventRepository_Update_Call{Call: _e.mock.On("Update", ctx, analysisEvent)}
}

func (_c *MockIAnalysisEventRepository_Update_Call) Run(run func(ctx context.Context, analysisEvent *entities.AnalysisEvent)) *MockIAnalysisEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.AnalysisEvent))
	})
	return _c
}

func (_c *MockIAnalysisEventRepository_Update_Call) Return(_a0 error) *MockIAnalysisEventRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAnalysisEventRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.AnalysisEvent) error) *MockIAnalysisEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAnalysisEventRepository creates a new instance of MockIAnalysisEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAnalysisEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAnalysisEventRepository {
	mock := &MockIAnalysisEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
