// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockICryptocurrencyProxy is an autogenerated mock type for the ICryptocurrencyProxy type
type MockICryptocurrencyProxy struct {
	mock.Mock
}

type MockICryptocurrencyProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICryptocurrencyProxy) EXPECT() *MockICryptocurrencyProxy_Expecter {
	return &MockICryptocurrencyProxy_Expecter{mock: &_m.Mock}
}

// FindCoinName provides a mock function with given fields: ctx, symbol
func (_m *MockICryptocurrencyProxy) FindCoinName(ctx context.Context, symbol string) (string, bool, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for FindCoinName")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, symbol)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICryptocurrencyProxy_FindCoinName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCoinName'
type MockICryptocurrencyProxy_FindCoinName_Call struct {
	*mock.Call
}

// FindCoinName is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MockICryptocurrencyProxy_Expecter) FindCoinName(ctx interface{}, symbol interface{}) *MockICryptocurrencyProxy_FindCoinName_Call {
	return &MockICryptocurrencyProxy_FindCoinName_Call{Call: _e.mock.On("FindCoinName", ctx, symbol)}
}

func (_c *MockICryptocurrencyProxy_FindCoinName_Call) Run(run func(ctx context.Context, symbol string)) *MockICryptocurrencyProxy_FindCoinName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockICryptocurrencyProxy_FindCoinName_Call) Return(_a0 string, _a1 bool, _a2 error) *MockICryptocurrencyProxy_FindCoinName_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICryptocurrencyProxy_FindCoinName_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *MockICryptocurrencyProxy_FindCoinName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICryptocurrencyProxy creates a new instance of MockICryptocurrencyProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICryptocurrencyProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICryptocurrencyProxy {
	mock := &MockICryptocurrencyProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
