// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/entities"

	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockISessionRunRepository is an autogenerated mock type for the ISessionRunRepository type
type MockISessionRunRepository struct {
	mock.Mock
}

type MockISessionRunRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionRunRepository) EXPECT() *MockISessionRunRepository_Expecter {
	return &MockISessionRunRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sessionRun
func (_m *MockISessionRunRepository) Create(ctx context.Context, sessionRun *entities.SessionRun) error {
	ret := _m.Called(ctx, sessionRun)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SessionRun) error); ok {
		r0 = rf(ctx, sessionRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRunRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockISessionRunRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionRun *entities.SessionRun
func (_e *MockISessionRunRepository_Expecter) Create(ctx interface{}, sessionRun interface{}) *MockISessionRunRepository_Create_Call {
	return &MockISessionRunRepository_Create_Call{Call: _e.mock.On("Create", ctx, sessionRun)}
}

func (_c *MockISessionRunRepository_Create_Call) Run(run func(ctx context.Context, sessionRun *entities.SessionRun)) *MockISessionRunRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SessionRun))
	})
	return _c
}

func (_c *MockISessionRunRepository_Create_Call) Return(_a0 error) *MockISessionRunRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRunRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.SessionRun) error) *MockISessionRunRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FailAllRunning provides a mock function with given fields: ctx, failureReason, finishedAt
func (_m *MockISessionRunRepository) FailAllRunning(ctx context.Context, failureReason string, finishedAt time.Time) error {
	ret := _m.Called(ctx, failureReason, finishedAt)

	if len(ret) == 0 {
		panic("no return value specified for FailAllRunning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, failureReason, finishedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRunRepository_FailAllRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailAllRunning'
type MockISessionRunRepository_FailAllRunning_Call struct {
	*mock.Call
}

// FailAllRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - failureReason string
//   - finishedAt time.Time
func (_e *MockISessionRunRepository_Expecter) FailAllRunning(ctx interface{}, failureReason interface{}, finishedAt interface{}) *MockISessionRunRepository_FailAllRunning_Call {
	return &MockISessionRunRepository_FailAllRunning_Call{Call: _e.mock.On("FailAllRunning", ctx, failureReason, finishedAt)}
}

func (_c *MockISessionRunRepository_FailAllRunning_Call) Run(run func(ctx context.Context, failureReason string, finishedAt time.Time)) *MockISessionRunRepository_FailAllRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockISessionRunRepository_FailAllRunning_Call) Return(_a0 error) *MockISessionRunRepository_FailAllRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRunRepository_FailAllRunning_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockISessionRunRepository_FailAllRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, sessionRun
func (_m *MockISessionRunRepository) Update(ctx context.Context, sessionRun *entities.SessionRun) error {
	ret := _m.Called(ctx, sessionRun)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SessionRun) error); ok {
		r0 = rf(ctx, sessionRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRunRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockISessionRunRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionRun *entities.SessionRun
func (_e *MockISessionRunRepository_Expecter) Update(ctx interface{}, sessionRun interface{}) *MockISessionRunRepository_Update_Call {
	return &MockISessionRunRepository_Update_Call{Call: _e.mock.On("Update", ctx, sessionRun)}
}

func (_c *MockISessionRunRepository_Update_Call) Run(run func(ctx context.Context, sessionRun *entities.SessionRun)) *MockISessionRunRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SessionRun))
	})
	return _c
}

func (_c *MockISessionRunRepository_Update_Call) Return(_a0 error) *MockISessionRunRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRunRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.SessionRun) error) *MockISessionRunRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISessionRunRepository creates a new instance of MockISessionRunRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionRunRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionRunRepository {
	mock := &MockISessionRunRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
