// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entities "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/entities"

	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIApiKeyRepository is an autogenerated mock type for the IApiKeyRepository type
type MockIApiKeyRepository struct {
	mock.Mock
}

type MockIApiKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIApiKeyRepository) EXPECT() *MockIApiKeyRepository_Expecter {
	return &MockIApiKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: apiKey
func (_m *MockIApiKeyRepository) Create(apiKey *entities.ApiKey) error {
	ret := _m.Called(apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.ApiKey) error); ok {
		r0 = rf(apiKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIApiKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIApiKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - apiKey *entities.ApiKey
func (_e *MockIApiKeyRepository_Expecter) Create(apiKey interface{}) *MockIApiKeyRepository_Create_Call {
	return &MockIApiKeyRepository_Create_Call{Call: _e.mock.On("Create", apiKey)}
}

func (_c *MockIApiKeyRepository_Create_Call) Run(run func(apiKey *entities.ApiKey)) *MockIApiKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.ApiKey))
	})
	return _c
}

func (_c *MockIApiKeyRepository_Create_Call) Return(_a0 error) *MockIApiKeyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIApiKeyRepository_Create_Call) RunAndReturn(run func(*entities.ApiKey) error) *MockIApiKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySecretHash provides a mock function with given fields: secretHash
func (_m *MockIApiKeyRepository) FindBySecretHash(secretHash string) (*entities.ApiKey, error) {
	ret := _m.Called(secretHash)

	if len(ret) == 0 {
		panic("no return value specified for FindBySecretHash")
	}

	var r0 *entities.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.ApiKey, error)); ok {
		return rf(secretHash)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.ApiKey); ok {
		r0 = rf(secretHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(secretHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIApiKeyRepository_FindBySecretHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySecretHash'
type MockIApiKeyRepository_FindBySecretHash_Call struct {
	*mock.Call
}

// FindBySecretHash is a helper method to define mock.On call
//   - secretHash string
func (_e *MockIApiKeyRepository_Expecter) FindBySecretHash(secretHash interface{}) *MockIApiKeyRepository_FindBySecretHash_Call {
	return &MockIApiKeyRepository_FindBySecretHash_Call{Call: _e.mock.On("FindBySecretHash", secretHash)}
}

func (_c *MockIApiKeyRepository_FindBySecretHash_Call) Run(run func(secretHash string)) *MockIApiKeyRepository_FindBySecretHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIApiKeyRepository_FindBySecretHash_Call) Return(_a0 *entities.ApiKey, _a1 error) *MockIApiKeyRepository_FindBySecretHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIApiKeyRepository_FindBySecretHash_Call) RunAndReturn(run func(string) (*entities.ApiKey, error)) *MockIApiKeyRepository_FindBySecretHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRevokedAt provides a mock function with given fields: apiKeyID, revokedAt
func (_m *MockIApiKeyRepository) UpdateRevokedAt(apiKeyID uint, revokedAt time.Time) error {
	ret := _m.Called(apiKeyID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRevokedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, time.Time) error); ok {
		r0 = rf(apiKeyID, revokedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIApiKeyRepository_UpdateRevokedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRevokedAt'
type MockIApiKeyRepository_UpdateRevokedAt_Call struct {
	*mock.Call
}

// UpdateRevokedAt is a helper method to define mock.On call
//   - apiKeyID uint
//   - revokedAt time.Time
func (_e *MockIApiKeyRepository_Expecter) UpdateRevokedAt(apiKeyID interface{}, revokedAt interface{}) *MockIApiKeyRepository_UpdateRevokedAt_Call {
	return &MockIApiKeyRepository_UpdateRevokedAt_Call{Call: _e.mock.On("UpdateRevokedAt", apiKeyID, revokedAt)}
}

func (_c *MockIApiKeyRepository_UpdateRevokedAt_Call) Run(run func(apiKeyID uint, revokedAt time.Time)) *MockIApiKeyRepository_UpdateRevokedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIApiKeyRepository_UpdateRevokedAt_Call) Return(_a0 error) *MockIApiKeyRepository_UpdateRevokedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIApiKeyRepository_UpdateRevokedAt_Call) RunAndReturn(run func(uint, time.Time) error) *MockIApiKeyRepository_UpdateRevokedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIApiKeyRepository creates a new instance of MockIApiKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIApiKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIApiKeyRepository {
	mock := &MockIApiKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
