// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIListedCompanyProxy is an autogenerated mock type for the IListedCompanyProxy type
type MockIListedCompanyProxy struct {
	mock.Mock
}

type MockIListedCompanyProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIListedCompanyProxy) EXPECT() *MockIListedCompanyProxy_Expecter {
	return &MockIListedCompanyProxy_Expecter{mock: &_m.Mock}
}

// FindCompanyShortName provides a mock function with given fields: ctx, stockCode
func (_m *MockIListedCompanyProxy) FindCompanyShortName(ctx context.Context, stockCode string) (string, bool, error) {
	ret := _m.Called(ctx, stockCode)

	if len(ret) == 0 {
		panic("no return value specified for FindCompanyShortName")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, stockCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, stockCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, stockCode)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, stockCode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIListedCompanyProxy_FindCompanyShortName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCompanyShortName'
type MockIListedCompanyProxy_FindCompanyShortName_Call struct {
	*mock.Call
}

// FindCompanyShortName is a helper method to define mock.On call
//   - ctx context.Context
//   - stockCode string
func (_e *MockIListedCompanyProxy_Expecter) FindCompanyShortName(ctx interface{}, stockCode interface{}) *MockIListedCompanyProxy_FindCompanyShortName_Call {
	return &MockIListedCompanyProxy_FindCompanyShortName_Call{Call: _e.mock.On("FindCompanyShortName", ctx, stockCode)}
}

func (_c *MockIListedCompanyProxy_FindCompanyShortName_Call) Run(run func(ctx context.Context, stockCode string)) *MockIListedCompanyProxy_FindCompanyShortName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIListedCompanyProxy_FindCompanyShortName_Call) Return(_a0 string, _a1 bool, _a2 error) *MockIListedCompanyProxy_FindCompanyShortName_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIListedCompanyProxy_FindCompanyShortName_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *MockIListedCompanyProxy_FindCompanyShortName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIListedCompanyProxy creates a new instance of MockIListedCompanyProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIListedCompanyProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIListedCompanyProxy {
	mock := &MockIListedCompanyProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
