// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockISessionGradeRepository is an autogenerated mock type for the ISessionGradeRepository type
type MockISessionGradeRepository struct {
	mock.Mock
}

type MockISessionGradeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionGradeRepository) EXPECT() *MockISessionGradeRepository_Expecter {
	return &MockISessionGradeRepository_Expecter{mock: &_m.Mock}
}

// DeleteExceptTradingDay provides a mock function with given fields: ctx, tradingDay
func (_m *MockISessionGradeRepository) DeleteExceptTradingDay(ctx context.Context, tradingDay string) error {
	ret := _m.Called(ctx, tradingDay)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExceptTradingDay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tradingDay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionGradeRepository_DeleteExceptTradingDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExceptTradingDay'
type MockISessionGradeRepository_DeleteExceptTradingDay_Call struct {
	*mock.Call
}

// DeleteExceptTradingDay is a helper method to define mock.On call
//   - ctx context.Context
//   - tradingDay string
func (_e *MockISessionGradeRepository_Expecter) DeleteExceptTradingDay(ctx interface{}, tradingDay interface{}) *MockISessionGradeRepository_DeleteExceptTradingDay_Call {
	return &MockISessionGradeRepository_DeleteExceptTradingDay_Call{Call: _e.mock.On("DeleteExceptTradingDay", ctx, tradingDay)}
}

func (_c *MockISessionGradeRepository_DeleteExceptTradingDay_Call) Run(run func(ctx context.Context, tradingDay string)) *MockISessionGradeRepository_DeleteExceptTradingDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockISessionGradeRepository_DeleteExceptTradingDay_Call) Return(_a0 error) *MockISessionGradeRepository_DeleteExceptTradingDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionGradeRepository_DeleteExceptTradingDay_Call) RunAndReturn(run func(context.Context, string) error) *MockISessionGradeRepository_DeleteExceptTradingDay_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTradingDay provides a mock function with given fields: ctx, symbol, category, tradingDay
func (_m *MockISessionGradeRepository) FindByTradingDay(ctx context.Context, symbol string, category string, tradingDay string) ([]entities.SessionGrade, error) {
	ret := _m.Called(ctx, symbol, category, tradingDay)

	if len(ret) == 0 {
		panic("no return value specified for FindByTradingDay")
	}

	var r0 []entities.SessionGrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]entities.SessionGrade, error)); ok {
		return rf(ctx, symbol, category, tradingDay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []entities.SessionGrade); ok {
		r0 = rf(ctx, symbol, category, tradingDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.SessionGrade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, symbol, category, tradingDay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionGradeRepository_FindByTradingDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTradingDay'
type MockISessionGradeRepository_FindByTradingDay_Call struct {
	*mock.Call
}

// FindByTradingDay is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - category string
//   - tradingDay string
func (_e *MockISessionGradeRepository_Expecter) FindByTradingDay(ctx interface{}, symbol interface{}, category interface{}, tradingDay interface{}) *MockISessionGradeRepository_FindByTradingDay_Call {
	return &MockISessionGradeRepository_FindByTradingDay_Call{Call: _e.mock.On("FindByTradingDay", ctx, symbol, category, tradingDay)}
}

func (_c *MockISessionGradeRepository_FindByTradingDay_Call) Run(run func(ctx context.Context, symbol string, category string, tradingDay string)) *MockISessionGradeRepository_FindByTradingDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockISessionGradeRepository_FindByTradingDay_Call) Return(_a0 []entities.SessionGrade, _a1 error) *MockISessionGradeRepository_FindByTradingDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionGradeRepository_FindByTradingDay_Call) RunAndReturn(run func(context.Context, string, string, string) ([]entities.SessionGrade, error)) *MockISessionGradeRepository_FindByTradingDay_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTradingDays provides a mock function with given fields: ctx, tradingDays
func (_m *MockISessionGradeRepository) FindByTradingDays(ctx context.Context, tradingDays []string) ([]entities.SessionGrade, error) {
	ret := _m.Called(ctx, tradingDays)

	if len(ret) == 0 {
		panic("no return value specified for FindByTradingDays")
	}

	var r0 []entities.SessionGrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]entities.SessionGrade, error)); ok {
		return rf(ctx, tradingDays)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []entities.SessionGrade); ok {
		r0 = rf(ctx, tradingDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.SessionGrade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, tradingDays)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionGradeRepository_FindByTradingDays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTradingDays'
type MockISessionGradeRepository_FindByTradingDays_Call struct {
	*mock.Call
}

// FindByTradingDays is a helper method to define mock.On call
//   - ctx context.Context
//   - tradingDays []string
func (_e *MockISessionGradeRepository_Expecter) FindByTradingDays(ctx interface{}, tradingDays interface{}) *MockISessionGradeRepository_FindByTradingDays_Call {
	return &MockISessionGradeRepository_FindByTradingDays_Call{Call: _e.mock.On("FindByTradingDays", ctx, tradingDays)}
}

func (_c *MockISessionGradeRepository_FindByTradingDays_Call) Run(run func(ctx context.Context, tradingDays []string)) *MockISessionGradeRepository_FindByTradingDays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockISessionGradeRepository_FindByTradingDays_Call) Return(_a0 []entities.SessionGrade, _a1 error) *MockISessionGradeRepository_FindByTradingDays_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionGradeRepository_FindByTradingDays_Call) RunAndReturn(run func(context.Context, []string) ([]entities.SessionGrade, error)) *MockISessionGradeRepository_FindByTradingDays_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, sessionGrade
func (_m *MockISessionGradeRepository) Save(ctx context.Context, sessionGrade *entities.SessionGrade) error {
	ret := _m.Called(ctx, sessionGrade)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.SessionGrade) error); ok {
		r0 = rf(ctx, sessionGrade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionGradeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockISessionGradeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionGrade *entities.SessionGrade
func (_e *MockISessionGradeRepository_Expecter) Save(ctx interface{}, sessionGrade interface{}) *MockISessionGradeRepository_Save_Call {
	return &MockISessionGradeRepository_Save_Call{Call: _e.mock.On("Save", ctx, sessionGrade)}
}

func (_c *MockISessionGradeRepository_Save_Call) Run(run func(ctx context.Context, sessionGrade *entities.SessionGrade)) *MockISessionGradeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.SessionGrade))
	})
	return _c
}

func (_c *MockISessionGradeRepository_Save_Call) Return(_a0 error) *MockISessionGradeRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionGradeRepository_Save_Call) RunAndReturn(run func(context.Context, *entities.SessionGrade) error) *MockISessionGradeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISessionGradeRepository creates a new instance of MockISessionGradeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionGradeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionGradeRepository {
	mock := &MockISessionGradeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
