// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	vo "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/vo"
	mock "github.com/stretchr/testify/mock"
)

// MockIPriceProxy is an autogenerated mock type for the IPriceProxy type
type MockIPriceProxy struct {
	mock.Mock
}

type MockIPriceProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPriceProxy) EXPECT() *MockIPriceProxy_Expecter {
	return &MockIPriceProxy_Expecter{mock: &_m.Mock}
}

// FetchPrice provides a mock function with given fields: ctx, symbol
func (_m *MockIPriceProxy) FetchPrice(ctx context.Context, symbol string) (vo.PriceQuoteVo, error) {
	ret := _m.Called(ctx, symbol)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrice")
	}

	var r0 vo.PriceQuoteVo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (vo.PriceQuoteVo, error)); ok {
		return rf(ctx, symbol)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) vo.PriceQuoteVo); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Get(0).(vo.PriceQuoteVo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPriceProxy_FetchPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrice'
type MockIPriceProxy_FetchPrice_Call struct {
	*mock.Call
}

// FetchPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
func (_e *MockIPriceProxy_Expecter) FetchPrice(ctx interface{}, symbol interface{}) *MockIPriceProxy_FetchPrice_Call {
	return &MockIPriceProxy_FetchPrice_Call{Call: _e.mock.On("FetchPrice", ctx, symbol)}
}

func (_c *MockIPriceProxy_FetchPrice_Call) Run(run func(ctx context.Context, symbol string)) *MockIPriceProxy_FetchPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIPriceProxy_FetchPrice_Call) Return(_a0 vo.PriceQuoteVo, _a1 error) *MockIPriceProxy_FetchPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPriceProxy_FetchPrice_Call) RunAndReturn(run func(context.Context, string) (vo.PriceQuoteVo, error)) *MockIPriceProxy_FetchPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPriceProxy creates a new instance of MockIPriceProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPriceProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPriceProxy {
	mock := &MockIPriceProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
