// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockICombinedGradeRepository is an autogenerated mock type for the ICombinedGradeRepository type
type MockICombinedGradeRepository struct {
	mock.Mock
}

type MockICombinedGradeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICombinedGradeRepository) EXPECT() *MockICombinedGradeRepository_Expecter {
	return &MockICombinedGradeRepository_Expecter{mock: &_m.Mock}
}

// DeleteExceptTradingDay provides a mock function with given fields: ctx, tradingDay
func (_m *MockICombinedGradeRepository) DeleteExceptTradingDay(ctx context.Context, tradingDay string) error {
	ret := _m.Called(ctx, tradingDay)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExceptTradingDay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tradingDay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICombinedGradeRepository_DeleteExceptTradingDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExceptTradingDay'
type MockICombinedGradeRepository_DeleteExceptTradingDay_Call struct {
	*mock.Call
}

// DeleteExceptTradingDay is a helper method to define mock.On call
//   - ctx context.Context
//   - tradingDay string
func (_e *MockICombinedGradeRepository_Expecter) DeleteExceptTradingDay(ctx interface{}, tradingDay interface{}) *MockICombinedGradeRepository_DeleteExceptTradingDay_Call {
	return &MockICombinedGradeRepository_DeleteExceptTradingDay_Call{Call: _e.mock.On("DeleteExceptTradingDay", ctx, tradingDay)}
}

func (_c *MockICombinedGradeRepository_DeleteExceptTradingDay_Call) Run(run func(ctx context.Context, tradingDay string)) *MockICombinedGradeRepository_DeleteExceptTradingDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockICombinedGradeRepository_DeleteExceptTradingDay_Call) Return(_a0 error) *MockICombinedGradeRepository_DeleteExceptTradingDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICombinedGradeRepository_DeleteExceptTradingDay_Call) RunAndReturn(run func(context.Context, string) error) *MockICombinedGradeRepository_DeleteExceptTradingDay_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, symbol, category
func (_m *MockICombinedGradeRepository) FindAll(ctx context.Context, symbol string, category string) ([]entities.CombinedGrade, error) {
	ret := _m.Called(ctx, symbol, category)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entities.CombinedGrade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entities.CombinedGrade, error)); ok {
		return rf(ctx, symbol, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entities.CombinedGrade); ok {
		r0 = rf(ctx, symbol, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CombinedGrade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, symbol, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICombinedGradeRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockICombinedGradeRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - symbol string
//   - category string
func (_e *MockICombinedGradeRepository_Expecter) FindAll(ctx interface{}, symbol interface{}, category interface{}) *MockICombinedGradeRepository_FindAll_Call {
	return &MockICombinedGradeRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, symbol, category)}
}

func (_c *MockICombinedGradeRepository_FindAll_Call) Run(run func(ctx context.Context, symbol string, category string)) *MockICombinedGradeRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockICombinedGradeRepository_FindAll_Call) Return(_a0 []entities.CombinedGrade, _a1 error) *MockICombinedGradeRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICombinedGradeRepository_FindAll_Call) RunAndReturn(run func(context.Context, string, string) ([]entities.CombinedGrade, error)) *MockICombinedGradeRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, combinedGrade
func (_m *MockICombinedGradeRepository) Save(ctx context.Context, combinedGrade *entities.CombinedGrade) error {
	ret := _m.Called(ctx, combinedGrade)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.CombinedGrade) error); ok {
		r0 = rf(ctx, combinedGrade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICombinedGradeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockICombinedGradeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - combinedGrade *entities.CombinedGrade
func (_e *MockICombinedGradeRepository_Expecter) Save(ctx interface{}, combinedGrade interface{}) *MockICombinedGradeRepository_Save_Call {
	return &MockICombinedGradeRepository_Save_Call{Call: _e.mock.On("Save", ctx, combinedGrade)}
}

func (_c *MockICombinedGradeRepository_Save_Call) Run(run func(ctx context.Context, combinedGrade *entities.CombinedGrade)) *MockICombinedGradeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.CombinedGrade))
	})
	return _c
}

func (_c *MockICombinedGradeRepository_Save_Call) Return(_a0 error) *MockICombinedGradeRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICombinedGradeRepository_Save_Call) RunAndReturn(run func(context.Context, *entities.CombinedGrade) error) *MockICombinedGradeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICombinedGradeRepository creates a new instance of MockICombinedGradeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICombinedGradeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICombinedGradeRepository {
	mock := &MockICombinedGradeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
