// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockITrackedSymbolRepository is an autogenerated mock type for the ITrackedSymbolRepository type
type MockITrackedSymbolRepository struct {
	mock.Mock
}

type MockITrackedSymbolRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITrackedSymbolRepository) EXPECT() *MockITrackedSymbolRepository_Expecter {
	return &MockITrackedSymbolRepository_Expecter{mock: &_m.Mock}
}

// FindTracking provides a mock function with given fields: ctx, category
func (_m *MockITrackedSymbolRepository) FindTracking(ctx context.Context, category string) ([]entities.TrackedSymbol, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for FindTracking")
	}

	var r0 []entities.TrackedSymbol
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.TrackedSymbol, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.TrackedSymbol); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TrackedSymbol)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITrackedSymbolRepository_FindTracking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTracking'
type MockITrackedSymbolRepository_FindTracking_Call struct {
	*mock.Call
}

// FindTracking is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
func (_e *MockITrackedSymbolRepository_Expecter) FindTracking(ctx interface{}, category interface{}) *MockITrackedSymbolRepository_FindTracking_Call {
	return &MockITrackedSymbolRepository_FindTracking_Call{Call: _e.mock.On("FindTracking", ctx, category)}
}

func (_c *MockITrackedSymbolRepository_FindTracking_Call) Run(run func(ctx context.Context, category string)) *MockITrackedSymbolRepository_FindTracking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITrackedSymbolRepository_FindTracking_Call) Return(_a0 []entities.TrackedSymbol, _a1 error) *MockITrackedSymbolRepository_FindTracking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITrackedSymbolRepository_FindTracking_Call) RunAndReturn(run func(context.Context, string) ([]entities.TrackedSymbol, error)) *MockITrackedSymbolRepository_FindTracking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITrackedSymbolRepository creates a new instance of MockITrackedSymbolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITrackedSymbolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITrackedSymbolRepository {
	mock := &MockITrackedSymbolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
