// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIRandomProxy is an autogenerated mock type for the IRandomProxy type
type MockIRandomProxy struct {
	mock.Mock
}

type MockIRandomProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRandomProxy) EXPECT() *MockIRandomProxy_Expecter {
	return &MockIRandomProxy_Expecter{mock: &_m.Mock}
}

// GenerateBytes provides a mock function with given fields: length
func (_m *MockIRandomProxy) GenerateBytes(length int) []byte {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBytes")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MockIRandomProxy_GenerateBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBytes'
type MockIRandomProxy_GenerateBytes_Call struct {
	*mock.Call
}

// GenerateBytes is a helper method to define mock.On call
//   - length int
func (_e *MockIRandomProxy_Expecter) GenerateBytes(length interface{}) *MockIRandomProxy_GenerateBytes_Call {
	return &MockIRandomProxy_GenerateBytes_Call{Call: _e.mock.On("GenerateBytes", length)}
}

func (_c *MockIRandomProxy_GenerateBytes_Call) Run(run func(length int)) *MockIRandomProxy_GenerateBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockIRandomProxy_GenerateBytes_Call) Return(_a0 []byte) *MockIRandomProxy_GenerateBytes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRandomProxy_GenerateBytes_Call) RunAndReturn(run func(int) []byte) *MockIRandomProxy_GenerateBytes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRandomProxy creates a new instance of MockIRandomProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRandomProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRandomProxy {
	mock := &MockIRandomProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
