// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	vo "github.com/CodeMachine0121/go-news-symbol-hunter/internal/domain/models/vo"
	mock "github.com/stretchr/testify/mock"
)

// MockIAnalystProxy is an autogenerated mock type for the IAnalystProxy type
type MockIAnalystProxy struct {
	mock.Mock
}

type MockIAnalystProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAnalystProxy) EXPECT() *MockIAnalystProxy_Expecter {
	return &MockIAnalystProxy_Expecter{mock: &_m.Mock}
}

// ModelName provides a mock function with no fields
func (_m *MockIAnalystProxy) ModelName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModelName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIAnalystProxy_ModelName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModelName'
type MockIAnalystProxy_ModelName_Call struct {
	*mock.Call
}

// ModelName is a helper method to define mock.On call
func (_e *MockIAnalystProxy_Expecter) ModelName() *MockIAnalystProxy_ModelName_Call {
	return &MockIAnalystProxy_ModelName_Call{Call: _e.mock.On("ModelName")}
}

func (_c *MockIAnalystProxy_ModelName_Call) Run(run func()) *MockIAnalystProxy_ModelName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIAnalystProxy_ModelName_Call) Return(_a0 string) *MockIAnalystProxy_ModelName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAnalystProxy_ModelName_Call) RunAndReturn(run func() string) *MockIAnalystProxy_ModelName_Call {
	_c.Call.Return(run)
	return _c
}

// Respond provides a mock function with given fields: ctx, request, exchanges
func (_m *MockIAnalystProxy) Respond(ctx context.Context, request vo.AnalystRequestVo, exchanges []vo.AnalystExchangeVo) (vo.AnalystTurnVo, error) {
	ret := _m.Called(ctx, request, exchanges)

	if len(ret) == 0 {
		panic("no return value specified for Respond")
	}

	var r0 vo.AnalystTurnVo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.AnalystRequestVo, []vo.AnalystExchangeVo) (vo.AnalystTurnVo, error)); ok {
		return rf(ctx, request, exchanges)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.AnalystRequestVo, []vo.AnalystExchangeVo) vo.AnalystTurnVo); ok {
		r0 = rf(ctx, request, exchanges)
	} else {
		r0 = ret.Get(0).(vo.AnalystTurnVo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.AnalystRequestVo, []vo.AnalystExchangeVo) error); ok {
		r1 = rf(ctx, request, exchanges)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAnalystProxy_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type MockIAnalystProxy_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - ctx context.Context
//   - request vo.AnalystRequestVo
//   - exchanges []vo.AnalystExchangeVo
func (_e *MockIAnalystProxy_Expecter) Respond(ctx interface{}, request interface{}, exchanges interface{}) *MockIAnalystProxy_Respond_Call {
	return &MockIAnalystProxy_Respond_Call{Call: _e.mock.On("Respond", ctx, request, exchanges)}
}

func (_c *MockIAnalystProxy_Respond_Call) Run(run func(ctx context.Context, request vo.AnalystRequestVo, exchanges []vo.AnalystExchangeVo)) *MockIAnalystProxy_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.AnalystRequestVo), args[2].([]vo.AnalystExchangeVo))
	})
	return _c
}

func (_c *MockIAnalystProxy_Respond_Call) Return(_a0 vo.AnalystTurnVo, _a1 error) *MockIAnalystProxy_Respond_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAnalystProxy_Respond_Call) RunAndReturn(run func(context.Context, vo.AnalystRequestVo, []vo.AnalystExchangeVo) (vo.AnalystTurnVo, error)) *MockIAnalystProxy_Respond_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAnalystProxy creates a new instance of MockIAnalystProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAnalystProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAnalystProxy {
	mock := &MockIAnalystProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
