// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIBackgroundJob is an autogenerated mock type for the IBackgroundJob type
type MockIBackgroundJob struct {
	mock.Mock
}

type MockIBackgroundJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBackgroundJob) EXPECT() *MockIBackgroundJob_Expecter {
	return &MockIBackgroundJob_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: ctx
func (_m *MockIBackgroundJob) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockIBackgroundJob_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIBackgroundJob_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIBackgroundJob_Expecter) Start(ctx interface{}) *MockIBackgroundJob_Start_Call {
	return &MockIBackgroundJob_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockIBackgroundJob_Start_Call) Run(run func(ctx context.Context)) *MockIBackgroundJob_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIBackgroundJob_Start_Call) Return() *MockIBackgroundJob_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBackgroundJob_Start_Call) RunAndReturn(run func(context.Context)) *MockIBackgroundJob_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockIBackgroundJob creates a new instance of MockIBackgroundJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBackgroundJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBackgroundJob {
	mock := &MockIBackgroundJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
