// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockIClockProxy is an autogenerated mock type for the IClockProxy type
type MockIClockProxy struct {
	mock.Mock
}

type MockIClockProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClockProxy) EXPECT() *MockIClockProxy_Expecter {
	return &MockIClockProxy_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with no fields
func (_m *MockIClockProxy) Now() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockIClockProxy_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockIClockProxy_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockIClockProxy_Expecter) Now() *MockIClockProxy_Now_Call {
	return &MockIClockProxy_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockIClockProxy_Now_Call) Run(run func()) *MockIClockProxy_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIClockProxy_Now_Call) Return(_a0 time.Time) *MockIClockProxy_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIClockProxy_Now_Call) RunAndReturn(run func() time.Time) *MockIClockProxy_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIClockProxy creates a new instance of MockIClockProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClockProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClockProxy {
	mock := &MockIClockProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
